name: Docker Image CI

on:
  push:
    branches: [ fdd/main ]
  pull_request:
    branches: [ fdd/main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ccussaguet/fast-data-dev-ssl:$(date +%s)
